### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by bvalot** [romueller/gefast#1]
Hi,

I'm interesting to used your program to analyses some metagenomics data. However, you give no help and no list of command line parameters that described how to use your program.

Thanks in advance,
Benoit

**Comment by romueller** [comment]
Hello Benoit,

Thanks for your interest and sorry for the inconvenience. A proper documentation and help function are in the making but not yet finished.

Until then, I hope that the following list of the most important parameters is helpful to you:

`--threshold / -t <integer>`
	Maximum number differences allowed between two amplicons (threshold t in the article). Default is 1. Corresponds to -d in Swarm.

`--sep-abundance <string>`
	Seperator symbol (string) between ID and abundance in a FASTA header line. Default is "_".
	
`--swarm-internal / -si <filename>`
	Name of the output file for internal structures. Corresponds to -i in Swarm.
	
`--swarm-output / -so <filename>`
	Name of the OTU output file. Corresponds to -o in Swarm.
	
`--swarm-statistics / -ss <filename>`
	Name of the statistics output file. Corresponds to -s in Swarm.
	
`--swarm-seeds / -sw <filename>`
	Name of the seeds output file. Corresponds to -w in Swarm.

`--swarm-uclust / -su <filename>`
	Name of the UCLUST-like output file. Corresponds to -u in Swarm.

`--swarm-fastidious / -sf`
	Activates fastidious clustering. Optional. Corresponds to -f in Swarm.

`--swarm-fastidious-threshold <integer>`
	Clustering threshold used during fastidious clustering (threshold t_f in the article). Default is 2 * t.
	
`--swarm-no-otu-breaking / -sn`
	Deactivates OTU breaking. Optional. Corresponds to -n in Swarm.
	 
`--swarm-mothur / -sr`
	Changes the output format to be compatible with mothur. Optional. Corresponds to -r in Swarm.
	
`--swarm-boundary / -sb <integer>`
	Minimum abundance for heavy OTUs (threshold b in the article). Default is 3. Corresponds to -b in Swarm. 

`--swarm-match-reward / -sm <integer>`
	Reward for a nucleotide match in alignments. Default is 5. Corresponds to -m in Swarm.
	
`--swarm-mismatch-penalty / -sp <integer>`
	Penalty for a nucleotide mismatch in alignments. Default is -4. Corresponds to -p in Swarm.
	
`--swarm-gap-opening-penalty / -sg <integer>`
	Penalty for opening a gap in alignments. Default is -12. Corresponds to -g in Swarm.
	
`--swarm-gap-extension-penalty / -se <integer>`
	Penalty for extending a gap in alignments. Default is -4. Corresponds to -e in Swarm.

`--use-score`
	Activates the scoring-function mode. Optional.

The input FASTA files have to be specified before any other parameter.	
Also, at least one of the output options (-si, -so, -ss, -sw, -su) has to be used.

So, a call of GeFaST could look like this:
`./GeFaST amplicons.fasta -so otus.txt -t 2 -sf`

Let me know if you need more information.

Regards,
Robert

**Comment by romueller** [comment]
The latest version of GeFaST comes with a help function and a manual.
