### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by sdewell** [romueller/gefast#2]
Hello!

Getting some make errors:

g++  -std=c++11 -pthread -O3 -msse4.1  -o build/objects/main.o -c main.cpp
g++  -std=c++11 -pthread -O3 -msse4.1  -o build/objects/src/Base.o -c src/Base.cpp
g++  -std=c++11 -pthread -O3 -msse4.1  -o build/objects/src/Preprocessor.o -c src/Preprocessor.cpp
g++  -std=c++11 -pthread -O3 -msse4.1  -o build/objects/src/SegmentFilter.o -c src/SegmentFilter.cpp
g++  -std=c++11 -pthread -O3 -msse4.1  -o build/objects/src/SIMD.o -c src/SIMD.cpp
g++  -std=c++11 -pthread -O3 -msse4.1  -o build/objects/src/SwarmClustering.o -c src/SwarmClustering.cpp
src/SwarmClustering.cpp: In function ‘void GeFaST::SwarmClustering::explorePool(const GeFaST::AmpliconCollection&, GeFaST::Matches&, std::vector<GeFaST::SwarmClustering::Otu*>&, const GeFaST::SwarmClustering::SwarmConfig&)’:
src/SwarmClustering.cpp:41:10: error: ‘iota’ is not a member of ‘std’
     std::iota(std::begin(index), std::end(index), 0);
          ^~~~
src/SwarmClustering.cpp:41:10: note: suggested alternative: ‘peta’
     std::iota(std::begin(index), std::end(index), 0);
          ^~~~
          peta
make: *** [build/objects/src/SwarmClustering.o] Error 1

**Comment by romueller** [comment]
Hello,
I cannot replicate that error. Which version of GCC are you using?

**Comment by sdewell** [comment]
looks like 5.5 via linuxbrew. i likely have a non-brew version as well ...
thank you!

g++ -v

COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure
--with-isl=/home/linuxbrew/.linuxbrew/opt/isl@0.18 --with-bugurl=
https://github.com/Linuxbrew/homebrew-core/issues
--prefix=/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4
--enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5
--with-gmp=/home/linuxbrew/.linuxbrew/opt/gmp
--with-mpfr=/home/linuxbrew/.linuxbrew/opt/mpfr
--with-mpc=/home/linuxbrew/.linuxbrew/opt/libmpc --enable-stage1-checking
--enable-checking=release --enable-lto --with-build-config=bootstrap-debug
--disable-werror --with-pkgversion='Homebrew gcc 5.5.0_4'
--with-boot-ldflags='-static-libstdc++ -static-libgcc ' --disable-nls
--disable-multilib
Thread model: posix
gcc version 5.5.0 (Homebrew gcc 5.5.0_4)

**Comment by romueller** [comment]
The GCC version should be high enough, although I am not familiar with potential peculiarities of the package manager you are using.

Could you try to compile and run a minimal example like the one below to test whether there is a general problem with std::iota in your C++ installation?
```
#include <iostream>
#include <numeric>
#include <vector>

int main(int argc, const char* argv[]) {
    std::vector<int> index(5);
    std::iota(std::begin(index), std::end(index), 0);
    for (auto i : index) std::cout << i << std::endl;
}
```

**Comment by sdewell** [comment]
thank you - will be traveling shortly but will take a look when I can.
appreciate it.

**Comment by dpryan79** [comment]
iota is defined in the numeric header:

```
--- src/SwarmClustering.cpp     2017-10-19 14:56:18.000000000 +0200
+++ src/SwarmClustering.cpp    2020-07-16 09:53:43.078715800 +0200
@@ -31,6 +31,7 @@
 #include <sstream>
 #include <thread>
 #include <unordered_set>
+#include <numeric>

 namespace GeFaST {

@@ -1465,4 +1466,4 @@

 }

-}
\ No newline at end of file
+}
```
