### ISSUE TITLE
Indexing error with some quality encodings

### ISSUE THREAD

**Issue by romueller** [romueller/gefast#7]
Quality encodings with a "from" value larger than 0 (among the implemented ones currently only Illumina 1.5+) lead to indexing errors in Dada2Utility::compute_lambda() when accessing the error matrix.

The offset is already subtracted from the quality scores handed over to compute_lambda() but the method expects the smallest quality score to read from the first column (index 0) of the error matrix. Therefore, the highest quality scores exceed the width of the error matrix.

**Comment by AROSLING** [comment]
At least in my test case, it seems that the offset is _not_ already subtracted from the quality scores before being handed to `compute_lambda()`.  I am using a recent Illumina MiSeq fastq for testing; VSEARCH confirms that the quality scores range from 35 to 71 (2 to 38 after subtracting offset 33).  My command line is:

```
build/GeFaST cons test/test.fastq /dev/null \
 --output_otus test/otus.clust \
 --preprocessor fastq \
 --clusterer cons-swarmer \
 --refiner cons-lsa \
 --quality_encoding illumina1.8 \
 --min_length 100
```

After my patch to detect out-of-bounds indexes, I get the error:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 67) >= this->size() (which is 42)
```

`compute_lambda()` is trying to access element 67; this clearly does not have the offset subtracted.

**Comment by brendanf** [comment]
At least in my test case, it seems that the offset is not already subtracted from the quality scores before being handed to `compute_lambda()`. I am using a recent Illumina MiSeq fastq for testing; VSEARCH confirms that the quality scores range from 35 to 71 (2 to 38 after subtracting offset 33). My command line is:

```
build/GeFaST cons test/test.fastq /dev/null \
 --output_otus test/otus.clust \
 --preprocessor fastq \
 --clusterer cons-swarmer \
 --refiner cons-lsa \
 --quality_encoding illumina1.8 \
 --min_length 100
```

After my patch to detect out-of-bounds indexes, I get the error:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 67) >= this->size() (which is 42)
```

`compute_lambda()` is trying to access element 67; this clearly does not have the offset subtracted.

**Comment by romueller** [comment]
I could finally reproduce the error. The offsets are subtracted but the latest work on the FastqPreprocessor introduced a tiny omission which, apparently, can lead to a similarly looking error. I am pretty sure I have identified the code causing this particular problem but could you please try the following two things on your test data set?

1) Run GeFaST as above but change how the quality scores of the dereplicated sequences are determined during the preprocessing step (using a configuration file with the entry `misc=score_derep:max`).
2) Modify the method `std::string MeanReadRepresentation::get_scores(const QualityEncoding<>& qe) const` in `Preprocessors.cpp` slightly by changing the assignment `=` in line 327 to `+=`. Then run GeFaST again as above (no configuration file needed this time).

I would very much appreciate if you could confirm whether it also prevents the error on your test data set.

**Comment by brendanf** [comment]
I can confirm that it works after either one of these changes.  Thanks!

**Comment by romueller** [comment]
Thanks for testing. The latest commit includes the fix described above. In addition, quality encodings with minimum scores other than zero are now handled correctly and should also no longer lead to out-of-bounds errors (checked with `.at()` on different data sets).
